name = "cf-drop"
main = "src/index.ts"
compatibility_date = "2025-01-02"

assets = { directory = "web/dist", binding = "ASSETS" }
# compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "cf-drop"
database_id = "83a6c66c-e5e6-4b2b-8590-d32c82380f05"

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "cf-drop"

[vars]
PASSWORD = "zdw7073!"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1
